### ISSUE TITLE
Flutter app inspection 

### ISSUE THREAD

**Issue by viswasaru** [jwisniewski/android-developer-assistant#15]
The Developer Assistant app  couldn't inspect flutter app. Is any possibility for flutter app

**Comment by jwisniewski** [comment]
@viswasaru I assume Developer Assistant doesn't detect specific elements on the screen, right? Developer Assistant depends mostly on the accessibility tree built by inspected applications. The same information is used by TalkBack, other assistants like Google Assistant and any accessibility service.

Looks like the inspected app doesn't generate any accessiblity tree.

I have found an issue on the Flutter project, which may be related: https://github.com/flutter/flutter/issues/111110

**Comment by jwisniewski** [comment]
According my recent knowledge, Developer Assistant would need to be ported from Android Assist API to Accessibility Service. That would be a larger change for this project, while benefits would be marginal. Flutter apps just don't depend on XML resources. Everything provided by the Accessibility Service API, would be a compatiility layer dedicated for accessibility tools, rather than developers, designers and testers this app aims to help.

I didn't decide yet to make this move.
